try: paraview.simple
except: from paraview.simple import *
paraview.simple._DisableFirstRenderCameraReset()

RenderView1 = CreateRenderView()
RenderView1.LightSpecularColor = [1.0, 1.0, 1.0]
RenderView1.UseOutlineForLODRendering = 0
RenderView1.KeyLightAzimuth = 10.0
RenderView1.UseTexturedBackground = 0
RenderView1.UseLight = 1
RenderView1.CameraPosition = [-0.436656408743753, 0.77204190707947995, 1.0467472730615099]
RenderView1.FillLightKFRatio = 3.0
RenderView1.Background2 = [0.0, 0.0, 0.16500000000000001]
RenderView1.FillLightAzimuth = -10.0
RenderView1.LODResolution = 0.5
RenderView1.BackgroundTexture = []
RenderView1.InteractionMode = '3D'
RenderView1.StencilCapable = 1
RenderView1.LightIntensity = 1.0
RenderView1.CameraFocalPoint = [3.45450344000764, -1.0314117267236, -0.38403729162136302]
RenderView1.ImageReductionFactor = 2
RenderView1.CameraViewAngle = 30.0
RenderView1.CameraParallelScale = 1.1701573536441701
RenderView1.EyeAngle = 2.0
RenderView1.HeadLightKHRatio = 3.0
RenderView1.StereoRender = 0
RenderView1.KeyLightIntensity = 0.75
RenderView1.BackLightAzimuth = 110.0
RenderView1.OrientationAxesInteractivity = 0
RenderView1.UseInteractiveRenderingForSceenshots = 0
RenderView1.UseOffscreenRendering = 0
RenderView1.Background = [1.0, 1.0, 1.0]
RenderView1.UseOffscreenRenderingForScreenshots = 0
RenderView1.NonInteractiveRenderDelay = 0.0
RenderView1.CenterOfRotation = [1.43456923961639, 0.223376401700079, 0.55308338254690204]
RenderView1.CameraParallelProjection = 0
RenderView1.CompressorConfig = 'vtkSquirtCompressor 0 3'
RenderView1.HeadLightWarmth = 0.5
RenderView1.MaximumNumberOfPeels = 4
RenderView1.LightDiffuseColor = [1.0, 1.0, 1.0]
RenderView1.StereoType = 'Red-Blue'
RenderView1.DepthPeeling = 1
RenderView1.BackLightKBRatio = 3.5
RenderView1.StereoCapableWindow = 1
RenderView1.CameraViewUp = [0.27630197164006509, -0.15618419056013205, 0.94829516453838836]
RenderView1.LightType = 'HeadLight'
RenderView1.LightAmbientColor = [1.0, 1.0, 1.0]
RenderView1.RemoteRenderThreshold = 3.0
RenderView1.CacheKey = 0.0
RenderView1.UseCache = 0
RenderView1.KeyLightElevation = 50.0
RenderView1.CenterAxesVisibility = 0
RenderView1.MaintainLuminance = 0
RenderView1.StillRenderImageReductionFactor = 1
RenderView1.BackLightWarmth = 0.5
RenderView1.FillLightElevation = -75.0
RenderView1.MultiSamples = 0
RenderView1.FillLightWarmth = 0.40000000000000002
RenderView1.AlphaBitPlanes = 1
RenderView1.LightSwitch = 0
RenderView1.OrientationAxesVisibility = 0
RenderView1.CameraClippingRange = [0.0053652829112034632, 5.3652829112034635]
RenderView1.BackLightElevation = 0.0
RenderView1.ViewTime = 0.0
RenderView1.OrientationAxesOutlineColor = [1.0, 1.0, 1.0]
RenderView1.LODThreshold = 22.100000000000001
RenderView1.CollectGeometryThreshold = 100.0
RenderView1.UseGradientBackground = 0
RenderView1.KeyLightWarmth = 0.59999999999999998
RenderView1.OrientationAxesLabelColor = [0.0, 0.0, 0.0]

Text1 = Text( guiName="Text1", Text='Surface Vectors\n(with Glyph)' )

shuttle_body_vtp = XMLPolyDataReader( guiName="shuttle_body.vtp", PointArrayStatus=['Momentum', 'Density', 'StagnationEnergy'], CellArrayStatus=[], FileName=['/Users/kmorel/data/sslv/body/shuttle_body.vtp'] )

Reflect1 = Reflect( guiName="Reflect1", CopyInput=1, Plane='Y', Center=0.0 )

Calculator1 = Calculator( guiName="Calculator1", Function='iHat', ReplacementValue=0.0, ResultArrayName='Result', ReplaceInvalidResults=1, AttributeMode='Point Data', CoordinateResults=0 )

ExtractSurface1 = ExtractSurface( guiName="ExtractSurface1", NonlinearSubdivisionLevel=1, PieceInvariant=1 )

GenerateSurfaceNormals1 = GenerateSurfaceNormals( guiName="GenerateSurfaceNormals1", FeatureAngle=30.0, PieceInvariant=1, Splitting=0, Consistency=1, FlipNormals=0, NonManifoldTraversal=0, ComputeCellNormals=0 )

SurfaceVectors1 = SurfaceVectors( guiName="SurfaceVectors1", SelectInputVectors=['POINTS', 'Result'], ConstraintMode='Parallel' )

Glyph1 = Glyph( guiName="Glyph1", KeepRandomPoints=0, MaskPoints=1, RandomMode=1, Vectors=['POINTS', 'Result'], GlyphTransform="Transform2", GlyphType="Arrow", Scalars=['POINTS', 'Density'], ScaleMode='vector', MaximumNumberofPoints=5000, SetScaleFactor=0.10000000000000001, Orient=1 )
Glyph1.GlyphType.TipRadius = 0.10000000000000001
Glyph1.GlyphTransform.Rotate = [0.0, 0.0, 0.0]
Glyph1.GlyphType.TipLength = 0.34999999999999998
Glyph1.GlyphType.TipResolution = 6
Glyph1.GlyphTransform.Translate = [0.0, 0.0, 0.0]
Glyph1.GlyphType.ShaftRadius = 0.029999999999999999
Glyph1.GlyphTransform.Scale = [1.0, 1.0, 1.0]
Glyph1.GlyphType.Invert = 0
Glyph1.GlyphType.ShaftResolution = 6

a1_MomentumMagSqr_PiecewiseFunction = CreatePiecewiseFunction( Points=[0.0, 0.0, 0.5, 0.0, 1.0, 1.0, 0.5, 0.0] )

a1_Density_PiecewiseFunction = CreatePiecewiseFunction( Points=[0.0, 0.0, 0.5, 0.0, 1.0, 1.0, 0.5, 0.0] )

a1_MomentumMagSqr_PVLookupTable = GetLookupTableForArray( "MomentumMagSqr", 1, Discretize=1, RGBPoints=[0.0, 0.23000000000000001, 0.29899999999999999, 0.754, 1.5624998328355399, 0.70599999999999996, 0.016, 0.14999999999999999], UseLogScale=0, VectorComponent=0, NanColor=[0.25, 0.0, 0.0], NumberOfTableValues=256, EnableOpacityMapping=0, ColorSpace='Diverging', IndexedLookup=0, VectorMode='Magnitude', ScalarOpacityFunction=a1_MomentumMagSqr_PiecewiseFunction, HSVWrap=0, ScalarRangeInitialized=1.0, AllowDuplicateScalars=1, Annotations=[], LockScalarRange=0 )

a1_Density_PVLookupTable = GetLookupTableForArray( "Density", 1, Discretize=1, RGBPoints=[0.039601042866706848, 0.23000000000000001, 0.29899999999999999, 0.754, 2.4679081439971924, 0.70599999999999996, 0.016, 0.14999999999999999], UseLogScale=0, VectorComponent=0, NanColor=[0.25, 0.0, 0.0], NumberOfTableValues=256, EnableOpacityMapping=0, ColorSpace='Diverging', IndexedLookup=0, VectorMode='Magnitude', ScalarOpacityFunction=a1_Density_PiecewiseFunction, HSVWrap=0, ScalarRangeInitialized=1.0, AllowDuplicateScalars=1, Annotations=[], LockScalarRange=0 )

SetActiveSource(Text1)
DataRepresentation5 = Show()
DataRepresentation5.Interactivity = 1
DataRepresentation5.Opacity = 1.0
DataRepresentation5.Justification = 'Left'
DataRepresentation5.Bold = 0
DataRepresentation5.Resizable = 0
DataRepresentation5.Color = [0.0, 0.0, 0.0]
DataRepresentation5.WindowLocation = 'AnyLocation'
DataRepresentation5.TextScaleMode = 'Viewport'
DataRepresentation5.Visibility = 1
DataRepresentation5.FontFamily = 'Times'
DataRepresentation5.FontSize = 24
DataRepresentation5.Italic = 0
DataRepresentation5.Position = [0.050000000000000003, 0.050000000000000003]
DataRepresentation5.Shadow = 0
DataRepresentation5.Position2 = [0.10000000000000001, 0.10000000000000001]
DataRepresentation5.Orientation = 0.0

SetActiveSource(shuttle_body_vtp)
DataRepresentation1 = Show()
DataRepresentation1.CubeAxesZAxisVisibility = 1
DataRepresentation1.SelectionPointLabelColor = [0.5, 0.5, 0.5]
DataRepresentation1.SelectionPointFieldDataArrayName = 'Density'
DataRepresentation1.SuppressLOD = 0
DataRepresentation1.CubeAxesXGridLines = 0
DataRepresentation1.BlockVisibility = []
DataRepresentation1.CubeAxesYAxisTickVisibility = 1
DataRepresentation1.Position = [0.0, 0.0, 0.0]
DataRepresentation1.BackfaceRepresentation = 'Follow Frontface'
DataRepresentation1.SelectionOpacity = 1.0
DataRepresentation1.SelectionPointLabelShadow = 0
DataRepresentation1.CubeAxesYGridLines = 0
DataRepresentation1.CubeAxesZAxisTickVisibility = 1
DataRepresentation1.OrientationMode = 'Direction'
DataRepresentation1.ScaleMode = 'No Data Scaling Off'
DataRepresentation1.Diffuse = 1.0
DataRepresentation1.SelectionUseOutline = 0
DataRepresentation1.CubeAxesZTitle = 'Z-Axis'
DataRepresentation1.Specular = 0.10000000000000001
DataRepresentation1.SelectionVisibility = 1
DataRepresentation1.InterpolateScalarsBeforeMapping = 1
DataRepresentation1.CustomRangeActive = [0, 0, 0]
DataRepresentation1.Origin = [0.0, 0.0, 0.0]
DataRepresentation1.CubeAxesVisibility = 0
DataRepresentation1.Scale = [1.0, 1.0, 1.0]
DataRepresentation1.SelectionCellLabelJustification = 'Left'
DataRepresentation1.DiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation1.SelectionCellLabelOpacity = 1.0
DataRepresentation1.Source = []
DataRepresentation1.Masking = 0
DataRepresentation1.Opacity = 1.0
DataRepresentation1.LineWidth = 1.0
DataRepresentation1.MeshVisibility = 0
DataRepresentation1.Visibility = 0
DataRepresentation1.SelectionCellLabelFontSize = 18
DataRepresentation1.CubeAxesCornerOffset = 0.0
DataRepresentation1.SelectionPointLabelJustification = 'Left'
DataRepresentation1.OriginalBoundsRangeActive = [0, 0, 0]
DataRepresentation1.SelectionPointLabelVisibility = 0
DataRepresentation1.SelectOrientationVectors = ''
DataRepresentation1.CubeAxesTickLocation = 'Inside'
DataRepresentation1.BackfaceDiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation1.CubeAxesYLabelFormat = '%-#6.3g'
DataRepresentation1.CubeAxesYAxisVisibility = 1
DataRepresentation1.SelectionPointLabelFontFamily = 'Arial'
DataRepresentation1.CubeAxesUseDefaultYTitle = 1
DataRepresentation1.SelectScaleArray = ''
DataRepresentation1.CubeAxesYTitle = 'Y-Axis'
DataRepresentation1.ColorAttributeType = 'POINT_DATA'
DataRepresentation1.AxesOrigin = [0.0, 0.0, 0.0]
DataRepresentation1.UserTransform = [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
DataRepresentation1.SpecularPower = 100.0
DataRepresentation1.Texture = []
DataRepresentation1.SelectionCellLabelShadow = 0
DataRepresentation1.AmbientColor = [0.0, 0.0, 0.0]
DataRepresentation1.BlockOpacity = {}
DataRepresentation1.MapScalars = 1
DataRepresentation1.PointSize = 2.0
DataRepresentation1.CubeAxesUseDefaultXTitle = 1
DataRepresentation1.SelectionCellLabelFormat = ''
DataRepresentation1.Scaling = 0
DataRepresentation1.StaticMode = 0
DataRepresentation1.SelectionCellLabelColor = [0.0, 1.0, 0.0]
DataRepresentation1.EdgeColor = [0.0, 0.0, 0.50000762951094835]
DataRepresentation1.CubeAxesXAxisTickVisibility = 1
DataRepresentation1.SelectionCellLabelVisibility = 0
DataRepresentation1.NonlinearSubdivisionLevel = 1
DataRepresentation1.CubeAxesColor = [0.0, 0.0, 0.0]
DataRepresentation1.Representation = 'Surface'
DataRepresentation1.CustomRange = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
DataRepresentation1.CustomBounds = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
DataRepresentation1.Orientation = [0.0, 0.0, 0.0]
DataRepresentation1.CubeAxesXTitle = 'X-Axis'
DataRepresentation1.CubeAxesInertia = 1
DataRepresentation1.BackfaceOpacity = 1.0
DataRepresentation1.SelectionPointLabelFontSize = 18
DataRepresentation1.SelectionCellFieldDataArrayName = 'vtkOriginalCellIds'
DataRepresentation1.SelectionColor = [1.0, 0.0, 1.0]
DataRepresentation1.BlockColor = {}
DataRepresentation1.Ambient = 0.0
DataRepresentation1.CubeAxesXAxisMinorTickVisibility = 1
DataRepresentation1.ScaleFactor = 0.21960260868072512
DataRepresentation1.BackfaceAmbientColor = [1.0, 1.0, 1.0]
DataRepresentation1.SelectMaskArray = ''
DataRepresentation1.SelectionLineWidth = 2.0
DataRepresentation1.CubeAxesZAxisMinorTickVisibility = 1
DataRepresentation1.CubeAxesXAxisVisibility = 1
DataRepresentation1.CubeAxesXLabelFormat = '%-#6.3g'
DataRepresentation1.Interpolation = 'Gouraud'
DataRepresentation1.CubeAxesZLabelFormat = '%-#6.3g'
DataRepresentation1.SelectionCellLabelFontFamily = 'Arial'
DataRepresentation1.SelectionCellLabelItalic = 0
DataRepresentation1.CubeAxesYAxisMinorTickVisibility = 1
DataRepresentation1.CubeAxesZGridLines = 0
DataRepresentation1.SelectionPointLabelFormat = ''
DataRepresentation1.SelectionPointLabelOpacity = 1.0
DataRepresentation1.UseAxesOrigin = 0
DataRepresentation1.CubeAxesFlyMode = 'Closest Triad'
DataRepresentation1.Pickable = 1
DataRepresentation1.CustomBoundsActive = [0, 0, 0]
DataRepresentation1.CubeAxesGridLineLocation = 'All Faces'
DataRepresentation1.SelectionRepresentation = 'Wireframe'
DataRepresentation1.SelectionPointLabelBold = 0
DataRepresentation1.ColorArrayName = ('POINT_DATA', '')
DataRepresentation1.SelectionPointLabelItalic = 0
DataRepresentation1.AllowSpecularHighlightingWithScalarColoring = 0
DataRepresentation1.SpecularColor = [1.0, 1.0, 1.0]
DataRepresentation1.CubeAxesUseDefaultZTitle = 1
DataRepresentation1.LookupTable = []
DataRepresentation1.SelectionPointSize = 5.0
DataRepresentation1.SelectionCellLabelBold = 0
DataRepresentation1.Orient = 0

SetActiveSource(Reflect1)
DataRepresentation2 = Show()
DataRepresentation2.CubeAxesZAxisVisibility = 1
DataRepresentation2.SelectionPointLabelColor = [0.5, 0.5, 0.5]
DataRepresentation2.SelectionPointFieldDataArrayName = 'Density'
DataRepresentation2.SuppressLOD = 0
DataRepresentation2.CubeAxesXGridLines = 0
DataRepresentation2.BlockVisibility = []
DataRepresentation2.CubeAxesYAxisTickVisibility = 1
DataRepresentation2.Position = [0.0, 0.0, 0.0]
DataRepresentation2.BackfaceRepresentation = 'Follow Frontface'
DataRepresentation2.SelectionOpacity = 1.0
DataRepresentation2.SelectionPointLabelShadow = 0
DataRepresentation2.CubeAxesYGridLines = 0
DataRepresentation2.CubeAxesZAxisTickVisibility = 1
DataRepresentation2.OrientationMode = 'Direction'
DataRepresentation2.ScaleMode = 'No Data Scaling Off'
DataRepresentation2.Diffuse = 1.0
DataRepresentation2.SelectionUseOutline = 0
DataRepresentation2.SelectionPointLabelFormat = ''
DataRepresentation2.CubeAxesZTitle = 'Z-Axis'
DataRepresentation2.Specular = 0.10000000000000001
DataRepresentation2.SelectionVisibility = 1
DataRepresentation2.InterpolateScalarsBeforeMapping = 1
DataRepresentation2.CustomRangeActive = [0, 0, 0]
DataRepresentation2.Origin = [0.0, 0.0, 0.0]
DataRepresentation2.CubeAxesVisibility = 0
DataRepresentation2.Scale = [1.0, 1.0, 1.0]
DataRepresentation2.SelectionCellLabelJustification = 'Left'
DataRepresentation2.DiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation2.SelectionCellLabelOpacity = 1.0
DataRepresentation2.CubeAxesInertia = 1
DataRepresentation2.Source = []
DataRepresentation2.Masking = 0
DataRepresentation2.Opacity = 1.0
DataRepresentation2.LineWidth = 1.0
DataRepresentation2.MeshVisibility = 0
DataRepresentation2.Visibility = 0
DataRepresentation2.SelectionCellLabelFontSize = 18
DataRepresentation2.CubeAxesCornerOffset = 0.0
DataRepresentation2.SelectionPointLabelJustification = 'Left'
DataRepresentation2.OriginalBoundsRangeActive = [0, 0, 0]
DataRepresentation2.SelectionPointLabelVisibility = 0
DataRepresentation2.SelectOrientationVectors = ''
DataRepresentation2.CubeAxesTickLocation = 'Inside'
DataRepresentation2.BackfaceDiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation2.CubeAxesYLabelFormat = '%-#6.3g'
DataRepresentation2.CubeAxesYAxisVisibility = 1
DataRepresentation2.SelectionPointLabelFontFamily = 'Arial'
DataRepresentation2.CubeAxesUseDefaultYTitle = 1
DataRepresentation2.SelectScaleArray = ''
DataRepresentation2.CubeAxesYTitle = 'Y-Axis'
DataRepresentation2.ColorAttributeType = 'POINT_DATA'
DataRepresentation2.AxesOrigin = [0.0, 0.0, 0.0]
DataRepresentation2.UserTransform = [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
DataRepresentation2.SpecularPower = 100.0
DataRepresentation2.Texture = []
DataRepresentation2.SelectionCellLabelShadow = 0
DataRepresentation2.AmbientColor = [0.0, 0.0, 0.0]
DataRepresentation2.BlockOpacity = {}
DataRepresentation2.MapScalars = 1
DataRepresentation2.PointSize = 2.0
DataRepresentation2.CubeAxesUseDefaultXTitle = 1
DataRepresentation2.SelectionCellLabelFormat = ''
DataRepresentation2.Scaling = 0
DataRepresentation2.StaticMode = 0
DataRepresentation2.SelectionCellLabelColor = [0.0, 1.0, 0.0]
DataRepresentation2.EdgeColor = [0.0, 0.0, 0.50000762951094835]
DataRepresentation2.CubeAxesXAxisTickVisibility = 1
DataRepresentation2.SelectionCellLabelVisibility = 0
DataRepresentation2.NonlinearSubdivisionLevel = 1
DataRepresentation2.CubeAxesColor = [0.0, 0.0, 0.0]
DataRepresentation2.Representation = 'Surface'
DataRepresentation2.CustomRange = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
DataRepresentation2.CustomBounds = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
DataRepresentation2.Orientation = [0.0, 0.0, 0.0]
DataRepresentation2.CubeAxesXTitle = 'X-Axis'
DataRepresentation2.ScalarOpacityUnitDistance = 0.044217716343396996
DataRepresentation2.BackfaceOpacity = 1.0
DataRepresentation2.SelectionPointLabelFontSize = 18
DataRepresentation2.SelectionCellFieldDataArrayName = 'vtkOriginalCellIds'
DataRepresentation2.SelectionColor = [1.0, 0.0, 1.0]
DataRepresentation2.BlockColor = {}
DataRepresentation2.Ambient = 0.0
DataRepresentation2.CubeAxesXAxisMinorTickVisibility = 1
DataRepresentation2.ScaleFactor = 0.21960260868072512
DataRepresentation2.BackfaceAmbientColor = [1.0, 1.0, 1.0]
DataRepresentation2.ScalarOpacityFunction = []
DataRepresentation2.SelectMaskArray = ''
DataRepresentation2.SelectionLineWidth = 2.0
DataRepresentation2.CubeAxesZAxisMinorTickVisibility = 1
DataRepresentation2.CubeAxesXAxisVisibility = 1
DataRepresentation2.CubeAxesXLabelFormat = '%-#6.3g'
DataRepresentation2.Interpolation = 'Gouraud'
DataRepresentation2.CubeAxesZLabelFormat = '%-#6.3g'
DataRepresentation2.SelectMapper = 'Projected tetra'
DataRepresentation2.SelectionCellLabelFontFamily = 'Arial'
DataRepresentation2.SelectionCellLabelItalic = 0
DataRepresentation2.CubeAxesYAxisMinorTickVisibility = 1
DataRepresentation2.CubeAxesZGridLines = 0
DataRepresentation2.ExtractedBlockIndex = 0
DataRepresentation2.SelectionPointLabelOpacity = 1.0
DataRepresentation2.UseAxesOrigin = 0
DataRepresentation2.CubeAxesFlyMode = 'Closest Triad'
DataRepresentation2.Pickable = 1
DataRepresentation2.CustomBoundsActive = [0, 0, 0]
DataRepresentation2.CubeAxesGridLineLocation = 'All Faces'
DataRepresentation2.SelectionRepresentation = 'Wireframe'
DataRepresentation2.SelectionPointLabelBold = 0
DataRepresentation2.ColorArrayName = ('POINT_DATA', '')
DataRepresentation2.SelectionPointLabelItalic = 0
DataRepresentation2.AllowSpecularHighlightingWithScalarColoring = 0
DataRepresentation2.SpecularColor = [1.0, 1.0, 1.0]
DataRepresentation2.CubeAxesUseDefaultZTitle = 1
DataRepresentation2.LookupTable = []
DataRepresentation2.SelectionPointSize = 5.0
DataRepresentation2.SelectionCellLabelBold = 0
DataRepresentation2.Orient = 0

SetActiveSource(Calculator1)
DataRepresentation3 = Show()
DataRepresentation3.CubeAxesZAxisVisibility = 1
DataRepresentation3.SelectionPointLabelColor = [0.5, 0.5, 0.5]
DataRepresentation3.SelectionPointFieldDataArrayName = 'Density'
DataRepresentation3.SuppressLOD = 0
DataRepresentation3.CubeAxesXGridLines = 0
DataRepresentation3.BlockVisibility = []
DataRepresentation3.CubeAxesYAxisTickVisibility = 1
DataRepresentation3.Position = [0.0, 0.0, 0.0]
DataRepresentation3.BackfaceRepresentation = 'Follow Frontface'
DataRepresentation3.SelectionOpacity = 1.0
DataRepresentation3.SelectionPointLabelShadow = 0
DataRepresentation3.CubeAxesYGridLines = 0
DataRepresentation3.CubeAxesZAxisTickVisibility = 1
DataRepresentation3.OrientationMode = 'Direction'
DataRepresentation3.ScaleMode = 'No Data Scaling Off'
DataRepresentation3.Diffuse = 1.0
DataRepresentation3.SelectionUseOutline = 0
DataRepresentation3.SelectionPointLabelFormat = ''
DataRepresentation3.CubeAxesZTitle = 'Z-Axis'
DataRepresentation3.Specular = 0.10000000000000001
DataRepresentation3.SelectionVisibility = 1
DataRepresentation3.InterpolateScalarsBeforeMapping = 1
DataRepresentation3.CustomRangeActive = [0, 0, 0]
DataRepresentation3.Origin = [0.0, 0.0, 0.0]
DataRepresentation3.CubeAxesVisibility = 0
DataRepresentation3.Scale = [1.0, 1.0, 1.0]
DataRepresentation3.SelectionCellLabelJustification = 'Left'
DataRepresentation3.DiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation3.SelectionCellLabelOpacity = 1.0
DataRepresentation3.CubeAxesInertia = 1
DataRepresentation3.Source = []
DataRepresentation3.Masking = 0
DataRepresentation3.Opacity = 1.0
DataRepresentation3.LineWidth = 1.0
DataRepresentation3.MeshVisibility = 0
DataRepresentation3.Visibility = 0
DataRepresentation3.SelectionCellLabelFontSize = 18
DataRepresentation3.CubeAxesCornerOffset = 0.0
DataRepresentation3.SelectionPointLabelJustification = 'Left'
DataRepresentation3.OriginalBoundsRangeActive = [0, 0, 0]
DataRepresentation3.SelectionPointLabelVisibility = 0
DataRepresentation3.SelectOrientationVectors = ''
DataRepresentation3.CubeAxesTickLocation = 'Inside'
DataRepresentation3.BackfaceDiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation3.CubeAxesYLabelFormat = '%-#6.3g'
DataRepresentation3.CubeAxesYAxisVisibility = 1
DataRepresentation3.SelectionPointLabelFontFamily = 'Arial'
DataRepresentation3.CubeAxesUseDefaultYTitle = 1
DataRepresentation3.SelectScaleArray = ''
DataRepresentation3.CubeAxesYTitle = 'Y-Axis'
DataRepresentation3.ColorAttributeType = 'POINT_DATA'
DataRepresentation3.AxesOrigin = [0.0, 0.0, 0.0]
DataRepresentation3.UserTransform = [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
DataRepresentation3.SpecularPower = 100.0
DataRepresentation3.Texture = []
DataRepresentation3.SelectionCellLabelShadow = 0
DataRepresentation3.AmbientColor = [0.0, 0.0, 0.0]
DataRepresentation3.BlockOpacity = {}
DataRepresentation3.MapScalars = 1
DataRepresentation3.PointSize = 2.0
DataRepresentation3.CubeAxesUseDefaultXTitle = 1
DataRepresentation3.SelectionCellLabelFormat = ''
DataRepresentation3.Scaling = 0
DataRepresentation3.StaticMode = 0
DataRepresentation3.SelectionCellLabelColor = [0.0, 1.0, 0.0]
DataRepresentation3.EdgeColor = [0.0, 0.0, 0.50000762951094835]
DataRepresentation3.CubeAxesXAxisTickVisibility = 1
DataRepresentation3.SelectionCellLabelVisibility = 0
DataRepresentation3.NonlinearSubdivisionLevel = 1
DataRepresentation3.CubeAxesColor = [0.0, 0.0, 0.0]
DataRepresentation3.Representation = 'Surface'
DataRepresentation3.CustomRange = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
DataRepresentation3.CustomBounds = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
DataRepresentation3.Orientation = [0.0, 0.0, 0.0]
DataRepresentation3.CubeAxesXTitle = 'X-Axis'
DataRepresentation3.ScalarOpacityUnitDistance = 0.044217716343396996
DataRepresentation3.BackfaceOpacity = 1.0
DataRepresentation3.SelectionPointLabelFontSize = 18
DataRepresentation3.SelectionCellFieldDataArrayName = 'vtkOriginalCellIds'
DataRepresentation3.SelectionColor = [1.0, 0.0, 1.0]
DataRepresentation3.BlockColor = {}
DataRepresentation3.Ambient = 0.0
DataRepresentation3.CubeAxesXAxisMinorTickVisibility = 1
DataRepresentation3.ScaleFactor = 0.21960260868072512
DataRepresentation3.BackfaceAmbientColor = [1.0, 1.0, 1.0]
DataRepresentation3.ScalarOpacityFunction = []
DataRepresentation3.SelectMaskArray = ''
DataRepresentation3.SelectionLineWidth = 2.0
DataRepresentation3.CubeAxesZAxisMinorTickVisibility = 1
DataRepresentation3.CubeAxesXAxisVisibility = 1
DataRepresentation3.CubeAxesXLabelFormat = '%-#6.3g'
DataRepresentation3.Interpolation = 'Gouraud'
DataRepresentation3.CubeAxesZLabelFormat = '%-#6.3g'
DataRepresentation3.SelectMapper = 'Projected tetra'
DataRepresentation3.SelectionCellLabelFontFamily = 'Arial'
DataRepresentation3.SelectionCellLabelItalic = 0
DataRepresentation3.CubeAxesYAxisMinorTickVisibility = 1
DataRepresentation3.CubeAxesZGridLines = 0
DataRepresentation3.ExtractedBlockIndex = 0
DataRepresentation3.SelectionPointLabelOpacity = 1.0
DataRepresentation3.UseAxesOrigin = 0
DataRepresentation3.CubeAxesFlyMode = 'Closest Triad'
DataRepresentation3.Pickable = 1
DataRepresentation3.CustomBoundsActive = [0, 0, 0]
DataRepresentation3.CubeAxesGridLineLocation = 'All Faces'
DataRepresentation3.SelectionRepresentation = 'Wireframe'
DataRepresentation3.SelectionPointLabelBold = 0
DataRepresentation3.ColorArrayName = ('POINT_DATA', '')
DataRepresentation3.SelectionPointLabelItalic = 0
DataRepresentation3.AllowSpecularHighlightingWithScalarColoring = 0
DataRepresentation3.SpecularColor = [1.0, 1.0, 1.0]
DataRepresentation3.CubeAxesUseDefaultZTitle = 1
DataRepresentation3.LookupTable = []
DataRepresentation3.SelectionPointSize = 5.0
DataRepresentation3.SelectionCellLabelBold = 0
DataRepresentation3.Orient = 0

SetActiveSource(ExtractSurface1)
DataRepresentation4 = Show()
DataRepresentation4.CubeAxesZAxisVisibility = 1
DataRepresentation4.SelectionPointLabelColor = [0.5, 0.5, 0.5]
DataRepresentation4.SelectionPointFieldDataArrayName = 'Density'
DataRepresentation4.SuppressLOD = 0
DataRepresentation4.CubeAxesXGridLines = 0
DataRepresentation4.BlockVisibility = []
DataRepresentation4.CubeAxesYAxisTickVisibility = 1
DataRepresentation4.Position = [0.0, 0.0, 0.0]
DataRepresentation4.BackfaceRepresentation = 'Follow Frontface'
DataRepresentation4.SelectionOpacity = 1.0
DataRepresentation4.SelectionPointLabelShadow = 0
DataRepresentation4.CubeAxesYGridLines = 0
DataRepresentation4.CubeAxesZAxisTickVisibility = 1
DataRepresentation4.OrientationMode = 'Direction'
DataRepresentation4.ScaleMode = 'No Data Scaling Off'
DataRepresentation4.Diffuse = 1.0
DataRepresentation4.SelectionUseOutline = 0
DataRepresentation4.CubeAxesZTitle = 'Z-Axis'
DataRepresentation4.Specular = 0.10000000000000001
DataRepresentation4.SelectionVisibility = 1
DataRepresentation4.InterpolateScalarsBeforeMapping = 1
DataRepresentation4.CustomRangeActive = [0, 0, 0]
DataRepresentation4.Origin = [0.0, 0.0, 0.0]
DataRepresentation4.CubeAxesVisibility = 0
DataRepresentation4.Scale = [1.0, 1.0, 1.0]
DataRepresentation4.SelectionCellLabelJustification = 'Left'
DataRepresentation4.DiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation4.SelectionCellLabelOpacity = 1.0
DataRepresentation4.Source = []
DataRepresentation4.Masking = 0
DataRepresentation4.Opacity = 1.0
DataRepresentation4.LineWidth = 1.0
DataRepresentation4.MeshVisibility = 0
DataRepresentation4.Visibility = 1
DataRepresentation4.SelectionCellLabelFontSize = 18
DataRepresentation4.CubeAxesCornerOffset = 0.0
DataRepresentation4.SelectionPointLabelJustification = 'Left'
DataRepresentation4.OriginalBoundsRangeActive = [0, 0, 0]
DataRepresentation4.SelectionPointLabelVisibility = 0
DataRepresentation4.SelectOrientationVectors = ''
DataRepresentation4.CubeAxesTickLocation = 'Inside'
DataRepresentation4.BackfaceDiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation4.CubeAxesYLabelFormat = '%-#6.3g'
DataRepresentation4.CubeAxesYAxisVisibility = 1
DataRepresentation4.SelectionPointLabelFontFamily = 'Arial'
DataRepresentation4.CubeAxesUseDefaultYTitle = 1
DataRepresentation4.SelectScaleArray = ''
DataRepresentation4.CubeAxesYTitle = 'Y-Axis'
DataRepresentation4.ColorAttributeType = 'POINT_DATA'
DataRepresentation4.AxesOrigin = [0.0, 0.0, 0.0]
DataRepresentation4.UserTransform = [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
DataRepresentation4.SpecularPower = 100.0
DataRepresentation4.Texture = []
DataRepresentation4.SelectionCellLabelShadow = 0
DataRepresentation4.AmbientColor = [0.0, 0.0, 0.0]
DataRepresentation4.BlockOpacity = {}
DataRepresentation4.MapScalars = 1
DataRepresentation4.PointSize = 2.0
DataRepresentation4.CubeAxesUseDefaultXTitle = 1
DataRepresentation4.SelectionCellLabelFormat = ''
DataRepresentation4.Scaling = 0
DataRepresentation4.StaticMode = 0
DataRepresentation4.SelectionCellLabelColor = [0.0, 1.0, 0.0]
DataRepresentation4.EdgeColor = [0.0, 0.0, 0.50000762951094835]
DataRepresentation4.CubeAxesXAxisTickVisibility = 1
DataRepresentation4.SelectionCellLabelVisibility = 0
DataRepresentation4.NonlinearSubdivisionLevel = 1
DataRepresentation4.CubeAxesColor = [0.0, 0.0, 0.0]
DataRepresentation4.Representation = 'Surface'
DataRepresentation4.CustomRange = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
DataRepresentation4.CustomBounds = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
DataRepresentation4.Orientation = [0.0, 0.0, 0.0]
DataRepresentation4.CubeAxesXTitle = 'X-Axis'
DataRepresentation4.CubeAxesInertia = 1
DataRepresentation4.BackfaceOpacity = 1.0
DataRepresentation4.SelectionPointLabelFontSize = 18
DataRepresentation4.SelectionCellFieldDataArrayName = 'vtkOriginalCellIds'
DataRepresentation4.SelectionColor = [1.0, 0.0, 1.0]
DataRepresentation4.BlockColor = {}
DataRepresentation4.Ambient = 0.0
DataRepresentation4.CubeAxesXAxisMinorTickVisibility = 1
DataRepresentation4.ScaleFactor = 0.21960260868072512
DataRepresentation4.BackfaceAmbientColor = [1.0, 1.0, 1.0]
DataRepresentation4.SelectMaskArray = ''
DataRepresentation4.SelectionLineWidth = 2.0
DataRepresentation4.CubeAxesZAxisMinorTickVisibility = 1
DataRepresentation4.CubeAxesXAxisVisibility = 1
DataRepresentation4.CubeAxesXLabelFormat = '%-#6.3g'
DataRepresentation4.Interpolation = 'Gouraud'
DataRepresentation4.CubeAxesZLabelFormat = '%-#6.3g'
DataRepresentation4.SelectionCellLabelFontFamily = 'Arial'
DataRepresentation4.SelectionCellLabelItalic = 0
DataRepresentation4.CubeAxesYAxisMinorTickVisibility = 1
DataRepresentation4.CubeAxesZGridLines = 0
DataRepresentation4.SelectionPointLabelFormat = ''
DataRepresentation4.SelectionPointLabelOpacity = 1.0
DataRepresentation4.UseAxesOrigin = 0
DataRepresentation4.CubeAxesFlyMode = 'Closest Triad'
DataRepresentation4.Pickable = 1
DataRepresentation4.CustomBoundsActive = [0, 0, 0]
DataRepresentation4.CubeAxesGridLineLocation = 'All Faces'
DataRepresentation4.SelectionRepresentation = 'Wireframe'
DataRepresentation4.SelectionPointLabelBold = 0
DataRepresentation4.ColorArrayName = ('POINT_DATA', '')
DataRepresentation4.SelectionPointLabelItalic = 0
DataRepresentation4.AllowSpecularHighlightingWithScalarColoring = 0
DataRepresentation4.SpecularColor = [1.0, 1.0, 1.0]
DataRepresentation4.CubeAxesUseDefaultZTitle = 1
DataRepresentation4.LookupTable = []
DataRepresentation4.SelectionPointSize = 5.0
DataRepresentation4.SelectionCellLabelBold = 0
DataRepresentation4.Orient = 0

SetActiveSource(GenerateSurfaceNormals1)
DataRepresentation5 = Show()
DataRepresentation5.CubeAxesZAxisVisibility = 1
DataRepresentation5.SelectionPointLabelColor = [0.5, 0.5, 0.5]
DataRepresentation5.SelectionPointFieldDataArrayName = 'Density'
DataRepresentation5.SuppressLOD = 0
DataRepresentation5.CubeAxesXGridLines = 0
DataRepresentation5.BlockVisibility = []
DataRepresentation5.CubeAxesYAxisTickVisibility = 1
DataRepresentation5.Position = [0.0, 0.0, 0.0]
DataRepresentation5.BackfaceRepresentation = 'Follow Frontface'
DataRepresentation5.SelectionOpacity = 1.0
DataRepresentation5.SelectionPointLabelShadow = 0
DataRepresentation5.CubeAxesYGridLines = 0
DataRepresentation5.CubeAxesZAxisTickVisibility = 1
DataRepresentation5.OrientationMode = 'Direction'
DataRepresentation5.ScaleMode = 'No Data Scaling Off'
DataRepresentation5.Diffuse = 1.0
DataRepresentation5.SelectionUseOutline = 0
DataRepresentation5.CubeAxesZTitle = 'Z-Axis'
DataRepresentation5.Specular = 0.10000000000000001
DataRepresentation5.SelectionVisibility = 1
DataRepresentation5.InterpolateScalarsBeforeMapping = 1
DataRepresentation5.CustomRangeActive = [0, 0, 0]
DataRepresentation5.Origin = [0.0, 0.0, 0.0]
DataRepresentation5.CubeAxesVisibility = 0
DataRepresentation5.Scale = [1.0, 1.0, 1.0]
DataRepresentation5.SelectionCellLabelJustification = 'Left'
DataRepresentation5.DiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation5.SelectionCellLabelOpacity = 1.0
DataRepresentation5.Source = []
DataRepresentation5.Masking = 0
DataRepresentation5.Opacity = 1.0
DataRepresentation5.LineWidth = 1.0
DataRepresentation5.MeshVisibility = 0
DataRepresentation5.Visibility = 0
DataRepresentation5.SelectionCellLabelFontSize = 18
DataRepresentation5.CubeAxesCornerOffset = 0.0
DataRepresentation5.SelectionPointLabelJustification = 'Left'
DataRepresentation5.OriginalBoundsRangeActive = [0, 0, 0]
DataRepresentation5.SelectionPointLabelVisibility = 0
DataRepresentation5.SelectOrientationVectors = ''
DataRepresentation5.CubeAxesTickLocation = 'Inside'
DataRepresentation5.BackfaceDiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation5.CubeAxesYLabelFormat = '%-#6.3g'
DataRepresentation5.CubeAxesYAxisVisibility = 1
DataRepresentation5.SelectionPointLabelFontFamily = 'Arial'
DataRepresentation5.CubeAxesUseDefaultYTitle = 1
DataRepresentation5.SelectScaleArray = ''
DataRepresentation5.CubeAxesYTitle = 'Y-Axis'
DataRepresentation5.ColorAttributeType = 'POINT_DATA'
DataRepresentation5.AxesOrigin = [0.0, 0.0, 0.0]
DataRepresentation5.UserTransform = [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
DataRepresentation5.SpecularPower = 100.0
DataRepresentation5.Texture = []
DataRepresentation5.SelectionCellLabelShadow = 0
DataRepresentation5.AmbientColor = [0.0, 0.0, 0.0]
DataRepresentation5.BlockOpacity = {}
DataRepresentation5.MapScalars = 1
DataRepresentation5.PointSize = 2.0
DataRepresentation5.CubeAxesUseDefaultXTitle = 1
DataRepresentation5.SelectionCellLabelFormat = ''
DataRepresentation5.Scaling = 0
DataRepresentation5.StaticMode = 0
DataRepresentation5.SelectionCellLabelColor = [0.0, 1.0, 0.0]
DataRepresentation5.EdgeColor = [0.0, 0.0, 0.50000762951094835]
DataRepresentation5.CubeAxesXAxisTickVisibility = 1
DataRepresentation5.SelectionCellLabelVisibility = 0
DataRepresentation5.NonlinearSubdivisionLevel = 1
DataRepresentation5.CubeAxesColor = [0.0, 0.0, 0.0]
DataRepresentation5.Representation = 'Surface'
DataRepresentation5.CustomRange = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
DataRepresentation5.CustomBounds = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
DataRepresentation5.Orientation = [0.0, 0.0, 0.0]
DataRepresentation5.CubeAxesXTitle = 'X-Axis'
DataRepresentation5.CubeAxesInertia = 1
DataRepresentation5.BackfaceOpacity = 1.0
DataRepresentation5.SelectionPointLabelFontSize = 18
DataRepresentation5.SelectionCellFieldDataArrayName = 'vtkOriginalCellIds'
DataRepresentation5.SelectionColor = [1.0, 0.0, 1.0]
DataRepresentation5.BlockColor = {}
DataRepresentation5.Ambient = 0.0
DataRepresentation5.CubeAxesXAxisMinorTickVisibility = 1
DataRepresentation5.ScaleFactor = 0.21960260868072512
DataRepresentation5.BackfaceAmbientColor = [1.0, 1.0, 1.0]
DataRepresentation5.SelectMaskArray = ''
DataRepresentation5.SelectionLineWidth = 2.0
DataRepresentation5.CubeAxesZAxisMinorTickVisibility = 1
DataRepresentation5.CubeAxesXAxisVisibility = 1
DataRepresentation5.CubeAxesXLabelFormat = '%-#6.3g'
DataRepresentation5.Interpolation = 'Gouraud'
DataRepresentation5.CubeAxesZLabelFormat = '%-#6.3g'
DataRepresentation5.SelectionCellLabelFontFamily = 'Arial'
DataRepresentation5.SelectionCellLabelItalic = 0
DataRepresentation5.CubeAxesYAxisMinorTickVisibility = 1
DataRepresentation5.CubeAxesZGridLines = 0
DataRepresentation5.SelectionPointLabelFormat = ''
DataRepresentation5.SelectionPointLabelOpacity = 1.0
DataRepresentation5.UseAxesOrigin = 0
DataRepresentation5.CubeAxesFlyMode = 'Closest Triad'
DataRepresentation5.Pickable = 1
DataRepresentation5.CustomBoundsActive = [0, 0, 0]
DataRepresentation5.CubeAxesGridLineLocation = 'All Faces'
DataRepresentation5.SelectionRepresentation = 'Wireframe'
DataRepresentation5.SelectionPointLabelBold = 0
DataRepresentation5.ColorArrayName = ('POINT_DATA', '')
DataRepresentation5.SelectionPointLabelItalic = 0
DataRepresentation5.AllowSpecularHighlightingWithScalarColoring = 0
DataRepresentation5.SpecularColor = [1.0, 1.0, 1.0]
DataRepresentation5.CubeAxesUseDefaultZTitle = 1
DataRepresentation5.LookupTable = []
DataRepresentation5.SelectionPointSize = 5.0
DataRepresentation5.SelectionCellLabelBold = 0
DataRepresentation5.Orient = 0

SetActiveSource(SurfaceVectors1)
DataRepresentation6 = Show()
DataRepresentation6.CubeAxesZAxisVisibility = 1
DataRepresentation6.SelectionPointLabelColor = [0.5, 0.5, 0.5]
DataRepresentation6.SelectionPointFieldDataArrayName = 'Density'
DataRepresentation6.SuppressLOD = 0
DataRepresentation6.CubeAxesXGridLines = 0
DataRepresentation6.BlockVisibility = []
DataRepresentation6.CubeAxesYAxisTickVisibility = 1
DataRepresentation6.Position = [0.0, 0.0, 0.0]
DataRepresentation6.BackfaceRepresentation = 'Follow Frontface'
DataRepresentation6.SelectionOpacity = 1.0
DataRepresentation6.SelectionPointLabelShadow = 0
DataRepresentation6.CubeAxesYGridLines = 0
DataRepresentation6.CubeAxesZAxisTickVisibility = 1
DataRepresentation6.OrientationMode = 'Direction'
DataRepresentation6.ScaleMode = 'No Data Scaling Off'
DataRepresentation6.Diffuse = 1.0
DataRepresentation6.SelectionUseOutline = 0
DataRepresentation6.CubeAxesZTitle = 'Z-Axis'
DataRepresentation6.Specular = 0.10000000000000001
DataRepresentation6.SelectionVisibility = 1
DataRepresentation6.InterpolateScalarsBeforeMapping = 1
DataRepresentation6.CustomRangeActive = [0, 0, 0]
DataRepresentation6.Origin = [0.0, 0.0, 0.0]
DataRepresentation6.CubeAxesVisibility = 0
DataRepresentation6.Scale = [1.0, 1.0, 1.0]
DataRepresentation6.SelectionCellLabelJustification = 'Left'
DataRepresentation6.DiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation6.SelectionCellLabelOpacity = 1.0
DataRepresentation6.Source = []
DataRepresentation6.Masking = 0
DataRepresentation6.Opacity = 1.0
DataRepresentation6.LineWidth = 1.0
DataRepresentation6.MeshVisibility = 0
DataRepresentation6.Visibility = 0
DataRepresentation6.SelectionCellLabelFontSize = 18
DataRepresentation6.CubeAxesCornerOffset = 0.0
DataRepresentation6.SelectionPointLabelJustification = 'Left'
DataRepresentation6.OriginalBoundsRangeActive = [0, 0, 0]
DataRepresentation6.SelectionPointLabelVisibility = 0
DataRepresentation6.SelectOrientationVectors = ''
DataRepresentation6.CubeAxesTickLocation = 'Inside'
DataRepresentation6.BackfaceDiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation6.CubeAxesYLabelFormat = '%-#6.3g'
DataRepresentation6.CubeAxesYAxisVisibility = 1
DataRepresentation6.SelectionPointLabelFontFamily = 'Arial'
DataRepresentation6.CubeAxesUseDefaultYTitle = 1
DataRepresentation6.SelectScaleArray = ''
DataRepresentation6.CubeAxesYTitle = 'Y-Axis'
DataRepresentation6.ColorAttributeType = 'POINT_DATA'
DataRepresentation6.AxesOrigin = [0.0, 0.0, 0.0]
DataRepresentation6.UserTransform = [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
DataRepresentation6.SpecularPower = 100.0
DataRepresentation6.Texture = []
DataRepresentation6.SelectionCellLabelShadow = 0
DataRepresentation6.AmbientColor = [0.0, 0.0, 0.0]
DataRepresentation6.BlockOpacity = {}
DataRepresentation6.MapScalars = 1
DataRepresentation6.PointSize = 2.0
DataRepresentation6.CubeAxesUseDefaultXTitle = 1
DataRepresentation6.SelectionCellLabelFormat = ''
DataRepresentation6.Scaling = 0
DataRepresentation6.StaticMode = 0
DataRepresentation6.SelectionCellLabelColor = [0.0, 1.0, 0.0]
DataRepresentation6.EdgeColor = [0.0, 0.0, 0.50000762951094835]
DataRepresentation6.CubeAxesXAxisTickVisibility = 1
DataRepresentation6.SelectionCellLabelVisibility = 0
DataRepresentation6.NonlinearSubdivisionLevel = 1
DataRepresentation6.CubeAxesColor = [0.0, 0.0, 0.0]
DataRepresentation6.Representation = 'Surface'
DataRepresentation6.CustomRange = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
DataRepresentation6.CustomBounds = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
DataRepresentation6.Orientation = [0.0, 0.0, 0.0]
DataRepresentation6.CubeAxesXTitle = 'X-Axis'
DataRepresentation6.CubeAxesInertia = 1
DataRepresentation6.BackfaceOpacity = 1.0
DataRepresentation6.SelectionPointLabelFontSize = 18
DataRepresentation6.SelectionCellFieldDataArrayName = 'vtkOriginalCellIds'
DataRepresentation6.SelectionColor = [1.0, 0.0, 1.0]
DataRepresentation6.BlockColor = {}
DataRepresentation6.Ambient = 0.0
DataRepresentation6.CubeAxesXAxisMinorTickVisibility = 1
DataRepresentation6.ScaleFactor = 0.21960260868072512
DataRepresentation6.BackfaceAmbientColor = [1.0, 1.0, 1.0]
DataRepresentation6.SelectMaskArray = ''
DataRepresentation6.SelectionLineWidth = 2.0
DataRepresentation6.CubeAxesZAxisMinorTickVisibility = 1
DataRepresentation6.CubeAxesXAxisVisibility = 1
DataRepresentation6.CubeAxesXLabelFormat = '%-#6.3g'
DataRepresentation6.Interpolation = 'Gouraud'
DataRepresentation6.CubeAxesZLabelFormat = '%-#6.3g'
DataRepresentation6.SelectionCellLabelFontFamily = 'Arial'
DataRepresentation6.SelectionCellLabelItalic = 0
DataRepresentation6.CubeAxesYAxisMinorTickVisibility = 1
DataRepresentation6.CubeAxesZGridLines = 0
DataRepresentation6.SelectionPointLabelFormat = ''
DataRepresentation6.SelectionPointLabelOpacity = 1.0
DataRepresentation6.UseAxesOrigin = 0
DataRepresentation6.CubeAxesFlyMode = 'Closest Triad'
DataRepresentation6.Pickable = 1
DataRepresentation6.CustomBoundsActive = [0, 0, 0]
DataRepresentation6.CubeAxesGridLineLocation = 'All Faces'
DataRepresentation6.SelectionRepresentation = 'Wireframe'
DataRepresentation6.SelectionPointLabelBold = 0
DataRepresentation6.ColorArrayName = ('POINT_DATA', '')
DataRepresentation6.SelectionPointLabelItalic = 0
DataRepresentation6.AllowSpecularHighlightingWithScalarColoring = 0
DataRepresentation6.SpecularColor = [1.0, 1.0, 1.0]
DataRepresentation6.CubeAxesUseDefaultZTitle = 1
DataRepresentation6.LookupTable = []
DataRepresentation6.SelectionPointSize = 5.0
DataRepresentation6.SelectionCellLabelBold = 0
DataRepresentation6.Orient = 0

SetActiveSource(Glyph1)
DataRepresentation7 = Show()
DataRepresentation7.CubeAxesZAxisVisibility = 1
DataRepresentation7.SelectionPointLabelColor = [0.5, 0.5, 0.5]
DataRepresentation7.SelectionPointFieldDataArrayName = 'Density'
DataRepresentation7.SuppressLOD = 0
DataRepresentation7.CubeAxesXGridLines = 0
DataRepresentation7.BlockVisibility = []
DataRepresentation7.CubeAxesYAxisTickVisibility = 1
DataRepresentation7.Position = [0.0, 0.0, 0.0]
DataRepresentation7.BackfaceRepresentation = 'Follow Frontface'
DataRepresentation7.SelectionOpacity = 1.0
DataRepresentation7.SelectionPointLabelShadow = 0
DataRepresentation7.CubeAxesYGridLines = 0
DataRepresentation7.CubeAxesZAxisTickVisibility = 1
DataRepresentation7.OrientationMode = 'Direction'
DataRepresentation7.ScaleMode = 'No Data Scaling Off'
DataRepresentation7.Diffuse = 1.0
DataRepresentation7.SelectionUseOutline = 0
DataRepresentation7.CubeAxesZTitle = 'Z-Axis'
DataRepresentation7.Specular = 0.10000000000000001
DataRepresentation7.SelectionVisibility = 1
DataRepresentation7.InterpolateScalarsBeforeMapping = 1
DataRepresentation7.CustomRangeActive = [0, 0, 0]
DataRepresentation7.Origin = [0.0, 0.0, 0.0]
DataRepresentation7.CubeAxesVisibility = 0
DataRepresentation7.Scale = [1.0, 1.0, 1.0]
DataRepresentation7.SelectionCellLabelJustification = 'Left'
DataRepresentation7.DiffuseColor = [0.28152895399404898, 0.90176241702906845, 0.0]
DataRepresentation7.SelectionCellLabelOpacity = 1.0
DataRepresentation7.Source = []
DataRepresentation7.Masking = 0
DataRepresentation7.Opacity = 1.0
DataRepresentation7.LineWidth = 1.0
DataRepresentation7.MeshVisibility = 0
DataRepresentation7.Visibility = 1
DataRepresentation7.SelectionCellLabelFontSize = 18
DataRepresentation7.CubeAxesCornerOffset = 0.0
DataRepresentation7.SelectionPointLabelJustification = 'Left'
DataRepresentation7.OriginalBoundsRangeActive = [0, 0, 0]
DataRepresentation7.SelectionPointLabelVisibility = 0
DataRepresentation7.SelectOrientationVectors = ''
DataRepresentation7.CubeAxesTickLocation = 'Inside'
DataRepresentation7.BackfaceDiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation7.CubeAxesYLabelFormat = '%-#6.3g'
DataRepresentation7.CubeAxesYAxisVisibility = 1
DataRepresentation7.SelectionPointLabelFontFamily = 'Arial'
DataRepresentation7.CubeAxesUseDefaultYTitle = 1
DataRepresentation7.SelectScaleArray = ''
DataRepresentation7.CubeAxesYTitle = 'Y-Axis'
DataRepresentation7.ColorAttributeType = 'POINT_DATA'
DataRepresentation7.AxesOrigin = [0.0, 0.0, 0.0]
DataRepresentation7.UserTransform = [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
DataRepresentation7.SpecularPower = 100.0
DataRepresentation7.Texture = []
DataRepresentation7.SelectionCellLabelShadow = 0
DataRepresentation7.AmbientColor = [0.0, 0.0, 0.0]
DataRepresentation7.BlockOpacity = {}
DataRepresentation7.MapScalars = 1
DataRepresentation7.PointSize = 2.0
DataRepresentation7.CubeAxesUseDefaultXTitle = 1
DataRepresentation7.SelectionCellLabelFormat = ''
DataRepresentation7.Scaling = 0
DataRepresentation7.StaticMode = 0
DataRepresentation7.SelectionCellLabelColor = [0.0, 1.0, 0.0]
DataRepresentation7.EdgeColor = [0.0, 0.0, 0.50000762951094835]
DataRepresentation7.CubeAxesXAxisTickVisibility = 1
DataRepresentation7.SelectionCellLabelVisibility = 0
DataRepresentation7.NonlinearSubdivisionLevel = 1
DataRepresentation7.CubeAxesColor = [0.0, 0.0, 0.0]
DataRepresentation7.Representation = 'Surface'
DataRepresentation7.CustomRange = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
DataRepresentation7.CustomBounds = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
DataRepresentation7.Orientation = [0.0, 0.0, 0.0]
DataRepresentation7.CubeAxesXTitle = 'X-Axis'
DataRepresentation7.CubeAxesInertia = 1
DataRepresentation7.BackfaceOpacity = 1.0
DataRepresentation7.SelectionPointLabelFontSize = 18
DataRepresentation7.SelectionCellFieldDataArrayName = 'vtkOriginalCellIds'
DataRepresentation7.SelectionColor = [1.0, 0.0, 1.0]
DataRepresentation7.BlockColor = {}
DataRepresentation7.Ambient = 0.0
DataRepresentation7.CubeAxesXAxisMinorTickVisibility = 1
DataRepresentation7.ScaleFactor = 0.2399839460849762
DataRepresentation7.BackfaceAmbientColor = [1.0, 1.0, 1.0]
DataRepresentation7.SelectMaskArray = ''
DataRepresentation7.SelectionLineWidth = 2.0
DataRepresentation7.CubeAxesZAxisMinorTickVisibility = 1
DataRepresentation7.CubeAxesXAxisVisibility = 1
DataRepresentation7.CubeAxesXLabelFormat = '%-#6.3g'
DataRepresentation7.Interpolation = 'Gouraud'
DataRepresentation7.CubeAxesZLabelFormat = '%-#6.3g'
DataRepresentation7.SelectionCellLabelFontFamily = 'Arial'
DataRepresentation7.SelectionCellLabelItalic = 0
DataRepresentation7.CubeAxesYAxisMinorTickVisibility = 1
DataRepresentation7.CubeAxesZGridLines = 0
DataRepresentation7.SelectionPointLabelFormat = ''
DataRepresentation7.SelectionPointLabelOpacity = 1.0
DataRepresentation7.UseAxesOrigin = 0
DataRepresentation7.CubeAxesFlyMode = 'Closest Triad'
DataRepresentation7.Pickable = 1
DataRepresentation7.CustomBoundsActive = [0, 0, 0]
DataRepresentation7.CubeAxesGridLineLocation = 'All Faces'
DataRepresentation7.SelectionRepresentation = 'Wireframe'
DataRepresentation7.SelectionPointLabelBold = 0
DataRepresentation7.ColorArrayName = ('POINT_DATA', '')
DataRepresentation7.SelectionPointLabelItalic = 0
DataRepresentation7.AllowSpecularHighlightingWithScalarColoring = 0
DataRepresentation7.SpecularColor = [1.0, 1.0, 1.0]
DataRepresentation7.CubeAxesUseDefaultZTitle = 1
DataRepresentation7.LookupTable = a1_Density_PVLookupTable
DataRepresentation7.SelectionPointSize = 5.0
DataRepresentation7.SelectionCellLabelBold = 0
DataRepresentation7.Orient = 0

Render()
